#!/usr/bin/env python3
"""
Extract Changed Helm Charts Script

PURPOSE:
  Identifies which Helm charts need to be packaged based on changed files.
  Distinguishes between parent charts and subcharts to avoid unnecessary builds.

USAGE:
  python3 extract_charts.py

INPUTS:
  - Reads: .github/outputs/all_changed_and_modified_files.json
    (Generated by tj-actions/changed-files GitHub Action)

OUTPUTS:
  - Sets GitHub environment variable: charts_to_package
    Space-separated list of chart paths (e.g., "platform platform/charts/pipeline-optimization")
  - Prints: "Charts to package: <list>"

BEHAVIOR:
  - Subcharts (*/charts/*): Always included when their files change
  - Parent charts: Only included when files outside charts/ subdirectory change
  - This prevents parent chart rebuilds when only subcharts are modified

EXAMPLES:
  Changed files: platform/charts/pipeline-optimization/values.yaml
  Output: platform/charts/pipeline-optimization

  Changed files: platform/values.yaml, platform/templates/deployment.yaml
  Output: platform

  Changed files: platform/values.yaml, platform/charts/pipeline-optimization/Chart.yaml
  Output: platform platform/charts/pipeline-optimization
"""
import json
import os
import sys

def set_github_env(name, value):
    if "GITHUB_ENV" in os.environ:
        with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"{name}<<EOF\n{value}\nEOF\n")

def main():
    try:
        with open('.github/outputs/all_changed_and_modified_files.json') as f:
            changed_files = json.load(f)
    except FileNotFoundError:
        print("'.github/outputs/all_changed_and_modified_files.json' not found. Assuming no files changed.")
        set_github_env("charts_to_package", "")
        return

    subcharts = set()
    parent_charts = set()

    for file_path in changed_files:
        # Exclude files in top directories starting with a dot
        if '/' in file_path and not file_path.startswith('.'):
            parts = file_path.split('/')

            # Check if this is a subchart (e.g., platform/charts/pipeline-optimization/...)
            if len(parts) >= 3 and parts[1] == 'charts':
                # This is a subchart path like: parent/charts/subchart/...
                subchart_dir = '/'.join(parts[:3])  # e.g., platform/charts/pipeline-optimization
                subcharts.add(subchart_dir)
            else:
                # This is a top-level/parent chart file (not in charts/ subdir)
                chart_dir = parts[0]
                parent_charts.add(chart_dir)

    # Combine: include all subcharts and only parent charts with direct changes
    potential_charts = subcharts | parent_charts

    charts_to_package = []
    for chart in sorted(list(potential_charts)):
        if os.path.isfile(os.path.join(chart, 'Chart.yaml')):
            charts_to_package.append(chart)

    charts_string = " ".join(charts_to_package)
    print(f"Charts to package: {charts_string}")

    set_github_env("charts_to_package", charts_string)

if __name__ == "__main__":
    main()
