#!/usr/bin/env python3
"""
Extract Changed Helm Charts Script

PURPOSE:
  Identifies which Helm charts need to be packaged based on Chart.yaml `version:`
  changes in the current push.

USAGE:
  python3 extract_charts.py

INPUTS:
  - Reads: .github/outputs/all_changed_and_modified_files.json
    (Generated by tj-actions/changed-files GitHub Action)
  - Reads: $GITHUB_EVENT_PATH to resolve the push's base SHA
  - Reads: $GITHUB_SHA for the head SHA

OUTPUTS:
  - Sets GitHub environment variable: charts_to_package
    Space-separated list of chart paths (e.g., "charts/platform charts/platform/charts/pipeline-optimization")
  - Prints: "Charts to package: <list>"

BEHAVIOR:
  - Considers only changed files matching charts/**/Chart.yaml.
  - For each, includes the chart directory only if the `version:` line
    changed in the push (git diff of before..head).
  - When the base SHA is unavailable (e.g. new-branch push), includes the
    chart and defers the check to check_chart_versions.py.
"""
import json
import os
import subprocess
import sys

def set_github_env(name, value):
    if "GITHUB_ENV" in os.environ:
        with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"{name}<<EOF\n{value}\nEOF\n")

def get_push_base_sha():
    """Resolve the base commit SHA for the current push event, or None if unavailable."""
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path or not os.path.isfile(event_path):
        return None
    try:
        with open(event_path) as f:
            event = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None
    before = event.get("before")
    # A zero SHA indicates a new branch push with no prior commit to diff against.
    if not before or set(before) == {"0"}:
        return None
    return before

def chart_yaml_version_changed(chart_yaml_path, base_sha, head_sha):
    """Return True if the `version:` line in chart_yaml_path changed between base_sha and head_sha.

    When the base SHA is not available (e.g. first push of a branch), fall back to True so
    the chart is still considered — check_chart_versions.py will catch unchanged versions.
    """
    if not base_sha:
        return True
    try:
        diff = subprocess.run(
            ["git", "diff", f"{base_sha}..{head_sha}", "--", chart_yaml_path],
            capture_output=True, text=True, check=True,
        ).stdout
    except subprocess.CalledProcessError as e:
        print(f"WARNING: git diff failed for {chart_yaml_path}: {e.stderr.strip()}. Including chart.", file=sys.stderr)
        return True
    for line in diff.splitlines():
        if (line.startswith("+version:") or line.startswith("-version:")) and not line.startswith(("+++", "---")):
            return True
    return False

def main():
    try:
        with open('.github/outputs/all_changed_and_modified_files.json') as f:
            changed_files = json.load(f)
    except FileNotFoundError:
        print("'.github/outputs/all_changed_and_modified_files.json' not found. Assuming no files changed.")
        set_github_env("charts_to_package", "")
        return

    base_sha = get_push_base_sha()
    head_sha = os.environ.get("GITHUB_SHA", "HEAD")

    candidate_charts = set()

    for file_path in changed_files:
        # The workflow only triggers on Chart.yaml changes, but guard anyway.
        if not file_path.startswith('charts/') or not file_path.endswith('/Chart.yaml'):
            continue

        if not chart_yaml_version_changed(file_path, base_sha, head_sha):
            print(f"Skipping {file_path}: version field unchanged")
            continue

        # Chart directory is the Chart.yaml's parent.
        candidate_charts.add(os.path.dirname(file_path))

    charts_to_package = []
    for chart in sorted(candidate_charts):
        if os.path.isfile(os.path.join(chart, 'Chart.yaml')):
            charts_to_package.append(chart)

    charts_string = " ".join(charts_to_package)
    print(f"Charts to package: {charts_string}")

    set_github_env("charts_to_package", charts_string)

if __name__ == "__main__":
    main()
