#!/usr/bin/env python3
"""
Extract Changed Helm Charts Script

PURPOSE:
  Identifies which Helm charts need to be packaged based on changed files.
  Distinguishes between parent charts and subcharts to avoid unnecessary builds.

USAGE:
  python3 extract_charts.py

INPUTS:
  - Reads: .github/outputs/all_changed_and_modified_files.json
    (Generated by tj-actions/changed-files GitHub Action)

OUTPUTS:
  - Sets GitHub environment variable: charts_to_package
    Space-separated list of chart paths (e.g., "charts/platform charts/platform/charts/pipeline-optimization")
  - Prints: "Charts to package: <list>"

BEHAVIOR:
  - All charts live under the top-level charts/ directory (e.g., charts/platform/).
  - Subcharts (charts/<parent>/charts/<subchart>): Always included when their files change
  - Parent charts: Only included when files outside their charts/ subdirectory change
  - This prevents parent chart rebuilds when only subcharts are modified

EXAMPLES:
  Changed files: charts/platform/charts/pipeline-optimization/values.yaml
  Output: charts/platform/charts/pipeline-optimization

  Changed files: charts/platform/values.yaml, charts/platform/templates/deployment.yaml
  Output: charts/platform

  Changed files: charts/platform/values.yaml, charts/platform/charts/pipeline-optimization/Chart.yaml
  Output: charts/platform charts/platform/charts/pipeline-optimization
"""
import json
import os
import sys

def set_github_env(name, value):
    if "GITHUB_ENV" in os.environ:
        with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"{name}<<EOF\n{value}\nEOF\n")

def main():
    try:
        with open('.github/outputs/all_changed_and_modified_files.json') as f:
            changed_files = json.load(f)
    except FileNotFoundError:
        print("'.github/outputs/all_changed_and_modified_files.json' not found. Assuming no files changed.")
        set_github_env("charts_to_package", "")
        return

    subcharts = set()
    parent_charts = set()

    for file_path in changed_files:
        # Only process files under the top-level charts/ directory
        if not file_path.startswith('charts/'):
            continue
        parts = file_path.split('/')

        # Path structure: charts/<parent>[/charts/<subchart>/...]
        # parts[0] = "charts", parts[1] = parent chart name
        if len(parts) < 2:
            continue

        # Check if this is a subchart (e.g., charts/platform/charts/pipeline-optimization/...)
        # parts: ['charts', 'platform', 'charts', 'pipeline-optimization', ...]
        if len(parts) >= 5 and parts[2] == 'charts':
            # This is a subchart path: charts/parent/charts/subchart/...
            subchart_dir = '/'.join(parts[:4])  # e.g., charts/platform/charts/pipeline-optimization
            subcharts.add(subchart_dir)
        else:
            # This is a parent chart file: charts/platform/...
            chart_dir = '/'.join(parts[:2])  # e.g., charts/platform
            parent_charts.add(chart_dir)

    # Combine: include all subcharts and only parent charts with direct changes
    potential_charts = subcharts | parent_charts

    charts_to_package = []
    for chart in sorted(list(potential_charts)):
        if os.path.isfile(os.path.join(chart, 'Chart.yaml')):
            charts_to_package.append(chart)

    charts_string = " ".join(charts_to_package)
    print(f"Charts to package: {charts_string}")

    set_github_env("charts_to_package", charts_string)

if __name__ == "__main__":
    main()
