# Copyright (c) 2026 Seqera Labs
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: agent-backend
description: Backend service for Seqera CLI AI capabilities
type: application
version: 1.2.1
appVersion: "1.13.1"
icon: https://raw.githubusercontent.com/seqeralabs/helm-charts/master/media/seqera-icon-light.svg
maintainers:
  - name: Seqera Labs
    email: devops@seqera.io
    url: https://seqera.io
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Seqera Docs
      url: https://docs.seqera.io
    - name: Helm charts repository
      url: https://github.com/seqeralabs/helm-charts/
  artifacthub.io/signKey: |
    fingerprint: F69F12932C6F3E0EED47964BCE031B0C243F50E0
    url: https://keybase.io/seqeradevops/pgp_keys.asc
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: "2.x.x"
  - name: seqera-common
    version: "3.x.x"
    repository: file://../../../seqera-common
    tags:
      - seqera-common
