{{/*
 Copyright (c) 2026 Seqera Labs
 All rights reserved.

 SPDX-License-Identifier: Apache-2.0

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/}}

{{- /* Don't use stringData in Secrets, as it may lead to weird glitches due to bugs in kubectl:
https://github.com/kubernetes/kubernetes/issues/89938
*/}}
{{- $commonLabels := include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | fromYaml -}}
{{- $mergedlabels := include "common.tplvalues.merge" (dict "values" (list .Values.secretLabels $commonLabels) "context" .) -}}
{{- $labels := include "common.tplvalues.render" (dict "value" $mergedlabels "context" $) -}}
{{- $mergedAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.secretAnnotations .Values.commonAnnotations) "context" .) -}}
{{- $annotations := include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
{{- if not (include "mcp.oidcToken.existingSecret" .) }}
  TOWER_OIDC_REGISTRATION_INITIAL_ACCESS_TOKEN: {{ include "common.secrets.passwords.manage" (dict "secret" (include "mcp.oidcToken.secretName" .) "key" (include "mcp.oidcToken.secretKey" .) "providedValues" (list "oidcToken.tokenString") "failOnNew" false "length" 32 "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if not (include "mcp.oauth.jwt.existingSecret" .) }}
  OAUTH_JWT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (include "mcp.oauth.jwt.existingSecret.secretName" .) "key" (include "mcp.oauth.jwt.existingSecret.secretKey" .) "providedValues" (list "oauth.jwtSeedString") "length" 40 "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if and (has "oauth" .Values.micronautEnvironments) .Values.oauth.clientSecretString (not (include "mcp.oauth.client.existingSecret" .)) }}
  OAUTH_CLIENT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (include "mcp.oauth.client.existingSecret.secretName" .) "key" (include "mcp.oauth.client.existingSecret.secretKey" .) "providedValues" (list "oauth.clientSecretString") "context" $ "honorProvidedValues" true) }}
{{- end }}
---
{{- if .Values.global.imageCredentials }}
# Only add the imagePullSecret template if it's defined.
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  .dockerconfigjson: {{ include "seqera.images.pullSecretCredentials" . | quote }}
{{- end }}
