{{- /* Don't use stringData in Secrets, as it may lead to weird glitches due to bugs in kubectl:
https://github.com/kubernetes/kubernetes/issues/89938
*/}}
{{- $commonLabels := include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | fromYaml -}}
{{- $mergedlabels := include "common.tplvalues.merge" (dict "values" (list .Values.platform.secretLabels $commonLabels) "context" .) -}}
{{- $labels := include "common.tplvalues.render" (dict "value" $mergedlabels "context" $) -}}
{{- $mergedAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.platform.secretAnnotations .Values.commonAnnotations) "context" .) -}}
{{- $annotations := include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
{{- if not (include "platform.database.existingSecret" .) }}
  TOWER_DB_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.database.secretName" .) "key" (include "platform.database.secretKey" .) "providedValues" (list "global.platformDatabase.password") "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if not (include "platform.license.existingSecret" .) }}
  TOWER_LICENSE: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.license.secretName" .) "key" (include "platform.license.secretKey" .) "providedValues" (list "platform.licenseString") "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if not (include "platform.jwt.existingSecret" .) }}
  TOWER_JWT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.jwt.secretName" .) "key" (include "platform.jwt.secretKey" .) "providedValues" (list "platform.jwtSeedString") "length" 35 "strong" true "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if not (include "platform.crypto.existingSecret" .) }}
  TOWER_CRYPTO_SECRETKEY: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.crypto.secretName" .) "key" (include "platform.crypto.secretKey" .) "providedValues" (list "platform.cryptoSeedString") "length" 35 "strong" true "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if or $.Values.redis.password $.Values.global.redis.password }}
  TOWER_REDIS_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.redis.secretName" .) "key" (include "platform.redis.secretKey" .) "providedValues" (list "redis.password" "global.redis.password") "context" $ "honorProvidedValues" true) }}
{{- end }}
{{- if and .Values.platform.smtp.host (not (include "platform.smtp.existingSecret" .)) }}
  TOWER_SMTP_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.smtp.secretName" .) "key" (include "platform.smtp.secretKey" .) "providedValues" (list "platform.smtp.password") "context" $ "honorProvidedValues" true) }}
{{- end }}
---
{{- if .Values.global.imageCredentials }}
# Only add the imagePullSecret template if it's defined.
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  .dockerconfigjson: {{ include "seqera.images.pullSecretCredentials" . | quote }}
{{- end }}
