{{/*
    Don't use stringData in Secrets, as it may lead to weird glitches due to bugs in kubectl:
    https://github.com/kubernetes/kubernetes/issues/89938
*/}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    {{- with .Values.tower.secretLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.tower.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.tower.secretAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  TOWER_SERVER_URL: {{ tpl .Values.global.platformUrl . | b64enc | quote }}
  TOWER_LANDING_URL: {{ tpl .Values.global.platformUrl . | b64enc | quote }}
  TOWER_CONTENT_URL: {{ include "tower.contentUrl" . | b64enc | quote }}

  WAVE_SERVER_URL: {{ tpl .Values.tower.waveServerUrl $ | b64enc | quote }}
  TOWER_ANALYTICS_URL: {{ tpl .Values.tower.analyticsUrl $ | b64enc | quote }}
  TOWER_ANALYTICS_SITE_ID: {{ .Values.tower.analyticsSiteId | toString | b64enc | quote }}

  TOWER_CONTACT_EMAIL: {{ .Values.tower.contactEmail | b64enc | quote }}
  TOWER_ENABLE_PLATFORMS: {{ .Values.tower.enablePlatforms | b64enc | quote }}
  TOWER_ENABLE_OPENAPI: {{ .Values.tower.enableOpenapi | b64enc | quote }}
  FLYWAY_LOCATIONS: {{ .Values.tower.flywayLocations | b64enc | quote }}
  TOWER_ROOT_USERS: {{ .Values.tower.rootUsers | b64enc | quote }}
  TOWER_RATELIMIT_REFRESH: {{ .Values.tower.ratelimitRefresh | b64enc | quote }}
  TOWER_RATELIMIT_PERIOD: {{ .Values.tower.ratelimitPeriod | toString | b64enc | quote }}
  TOWER_ENABLE_UNSAFE_MODE: {{ .Values.tower.enableHTTPUnsafeMode | b64enc | quote }}

  {{- if not .Values.tower.jwtSeedSecretName }}
  TOWER_JWT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-backend" (include "common.names.fullname" .)) "key" "TOWER_JWT_SECRET" "providedValues" (list "tower.jwtSeedString") "length" 35 "strong" true "context" $) }}
  {{- end }}
  {{- if not .Values.tower.cryptoSeedSecretName }}
  TOWER_CRYPTO_SECRETKEY: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-backend" (include "common.names.fullname" .)) "key" "TOWER_CRYPTO_SECRETKEY" "providedValues" (list "tower.cryptoSeedString") "length" 35 "strong" true "context" $) }}
  {{- end }}
  {{- if .Values.tower.licenseString }}
  TOWER_LICENSE: {{ .Values.tower.licenseString | b64enc | quote }}
  {{- end }}

  TOWER_LOG_PATTERN: {{ .Values.tower.logPattern | b64enc | quote }}
  TOWER_LOG_DIR: {{ .Values.tower.logDir | b64enc | quote }}
  TOWER_EVAL_TEAM_ID: {{ .Values.tower.evalTeamId | toString | b64enc | quote }}
  TOWER_EVAL_WORKSPACE_ID: {{ .Values.tower.evalWorkspaceId | toString | b64enc | quote }}
  TOWER_EVAL_MAX_TIME: {{ .Values.tower.evalMaxTime | b64enc | quote }}

  {{- if .Values.tower.hubspotApiKey }}
  TOWER_HUBSPOT_API_KEY: {{ .Values.tower.hubspotApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.tower.hubspotApiCallDelay }}
  TOWER_HUBSPOT_CALL_DELAY: {{ .Values.tower.hubspotApiCallDelay | b64enc | quote }}
  {{- end }}
  {{- if .Values.tower.hubspotDelay }}
  TOWER_HUBSPOT_DELAY: {{ .Values.tower.hubspotDelay | b64enc | quote }}
  {{- end }}
  {{- if .Values.tower.hubspotInterval }}
  TOWER_HUBSPOT_INTERVAL: {{ .Values.tower.hubspotInterval | b64enc | quote }}
  {{- end }}
  TOWER_MONITORING_ENV: {{ .Values.tower.monitoringEnv | b64enc | quote }}

  # When the dataExplorerAllowedWorkspaces variable is unset, it will enable the feature
  # for all workspaces, if set to empty string it will disable it for all workspaces.
  # An empty string is considered a boolean false, but we want it to be passed on in that case.
  # Instead, we don't want to have the env variable defined if no helm var is defined.
  #
  #
  # TODO: enable this by default now?
  #
  #
  {{- if or .Values.tower.dataExplorerAllowedWorkspaces (eq .Values.tower.dataExplorerAllowedWorkspaces "") }}
  TOWER_DATA_EXPLORER_ALLOWED_WORKSPACES: {{ .Values.tower.dataExplorerAllowedWorkspaces | toString | b64enc | quote }}
  {{- end }}

  JAVA_OPTS: {{ .Values.tower.javaOpts | b64enc | quote }}

  TOWER_GITHUB_CLIENT: {{ .Values.tower.githubClient | b64enc | quote }}
  TOWER_GITHUB_SECRET: {{ .Values.tower.githubSecret | b64enc | quote }}
  TOWER_GOOGLE_CLIENT: {{ .Values.tower.googleClient | b64enc | quote }}
  TOWER_GOOGLE_SECRET: {{ .Values.tower.googleSecret | b64enc | quote }}
  TOWER_OIDC_CLIENT: {{ .Values.tower.oidcClient | b64enc | quote }}
  TOWER_OIDC_SECRET: {{ .Values.tower.oidcSecret | b64enc | quote }}
  TOWER_OIDC_ISSUER: {{ .Values.tower.oidcIssuer | b64enc | quote }}
  TOWER_CDC_CLIENT: {{ .Values.tower.cdcClient | b64enc | quote }}
  TOWER_CDC_SECRET: {{ .Values.tower.cdcSecret | b64enc | quote }}

  {{ include "tower.emailSetup" . }}

  TOWER_DB_URL: {{ printf "jdbc:mysql://%s:%d/%s?&usePipelineAuth=false&useBatchMultiSend=false&permitMysqlScheme=true"
                          .Values.global.platformDatabase.host
                          (.Values.global.platformDatabase.port | int)
                          .Values.global.platformDatabase.database
                              | b64enc | quote }}
  TOWER_DB_USER: {{ tpl .Values.global.platformDatabase.username . | b64enc | quote }}
  {{/* The DB is password defined directly on the deployments as it may come from an external secret. */}}

  TOWER_DB_DRIVER: {{ .Values.tower.db.driver | b64enc | quote }}
  TOWER_DB_DIALECT: {{ .Values.tower.db.dialect | b64enc | quote }}
  TOWER_DB_MIN_POOL_SIZE: {{ .Values.tower.db.minPoolSize | toString | b64enc | quote }}
  TOWER_DB_MAX_POOL_SIZE: {{ .Values.tower.db.maxPoolSize | toString | b64enc | quote }}
  TOWER_DB_MAX_LIFETIME: {{ .Values.tower.db.maxLifetime | toString | b64enc | quote }}

  TOWER_REDIS_URL: {{ include "platform.redis.uri" . | b64enc | quote }}

  {{- if and .Values.tower.metering.platformId (not .Values.tower.metering.existingSecret) }}
  METERING_METRONOME_TOKEN: {{ .Values.tower.metering.token | b64enc | quote }}
  {{- end }}

{{- if .Values.global.imageCredentials }}
# Only add the imagePullSecret template if it's defined.
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    {{- with .Values.tower.secretLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.tower.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.tower.secretAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ include "imagePullSecret" . | quote }}
{{- end }}
