{{/*
    Don't use stringData in Secrets, as it may lead to weird glitches due to bugs in kubectl:
    https://github.com/kubernetes/kubernetes/issues/89938
*/}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    {{- with .Values.tower.secretLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.tower.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.tower.secretAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  TOWER_LICENSE: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.license.secretName" .) "key" (tpl .Values.tower.licenseSecretKey .) "providedValues" (list "tower.licenseString") "context" $) }}
  TOWER_JWT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.jwt.secretName" .) "key" (tpl .Values.tower.jwtSeedSecretKey .) "providedValues" (list "tower.jwtSeedString") "length" 35 "strong" true "context" $) }}
  TOWER_CRYPTO_SECRETKEY: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.crypto.secretName" .) "key" (tpl .Values.tower.cryptoSeedSecretKey .) "providedValues" (list "tower.cryptoSeedString") "length" 35 "strong" true "context" $) }}

  {{- if or .Values.redis.auth.enabled .Values.global.redis.auth.enabled }}
  TOWER_REDIS_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.redis.secretName" .) "key" (include "platform.redis.secretKey" .) "providedValues" (list "redis.auth.password" "global.redis.auth.password") "context" $) }}
  {{- end }}

  {{- if .Values.tower.smtp.host }}
  TOWER_SMTP_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" (include "platform.smtp.secretName" .) "key" (tpl .Values.tower.smtp.existingSecretKey .) "providedValues" (list "tower.smtp.password") "context" $) }}
  {{- end }}
---
{{- if .Values.global.imageCredentials }}
# Only add the imagePullSecret template if it's defined.
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    {{- with .Values.tower.secretLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.tower.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.tower.secretAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ include "imagePullSecret" . | quote }}
{{- end }}
