{{ if not .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.serviceAccount.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
imagePullSecrets:
  {{/* Include the global image pull secret if configured, and any additional secrets requested by the user. */}}
  {{- if .Values.global.imageCredentials }}
  - name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  {{- end }}
  {{- range .Values.serviceAccount.imagePullSecretNames }}
  - name: {{ . }}
  {{- end }}
{{ end }}
