{{ if not .Values.serviceAccount.name }}
  {{- $commonLabels := include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | fromYaml -}}
  {{- $labels := include "common.tplvalues.render" (dict "value" $commonLabels "context" $) -}}
  {{- $mergedAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.serviceAccount.annotations .Values.commonAnnotations) "context" .) -}}
  {{- $annotations := include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
imagePullSecrets:
  {{/* Include the global image pull secret if configured, and any additional secrets requested by the user. */}}
  {{- if .Values.global.imageCredentials }}
  - name: {{ printf "%s-imagepullsecret" (include "common.names.fullname" .) }}
  {{- end }}
  {{- range .Values.serviceAccount.imagePullSecretNames }}
  - name: {{ . }}
  {{- end }}
{{ end }}
